- name: Create security group
  local_action:
    module: ec2_group
    name: "{{ sec_name }}"
    description: sg for provisioned instance
    profile: "{{ profile }}"
    region: us-east-2
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Create EC2 instance
  local_action: 
    module: ec2
    group: "{{ sec_name }}"
    instance_type: "{{ instance_type}}"
    image: "{{ image }}"
    profile: "{{ profile }}"
    wait: true
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    count: "{{ count }}"
  register: ec2

- name: Adding instance to temp inventory
  add_host: 
    hostname: "{{ item.public_ip }}"
    group: test_new
  with_items: "{{ ec2.instances }}"

- name: Add public ip to hosts file
  local_action: lineinfile
    dest="./hosts" 
    regexp={{ item.public_ip }}
    insertafter=[kubernetes] line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Add private ip to hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.private_ip }}
    insertafter="[kubernetes]" line={{ item.private_ip }}
  with_items: "{{ ec2.instances }}"

- name: Waiting for ssh key
  local_action: wait_for
    host="{{ item.public_ip }}"
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Adding tag to instance
  local_action: ec2_tag
    resource="{{ item.id }}"
    region="{{ region }}"
    profile="{{ profile }}"
    state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      name: "ansible-lauched"
